### ISSUE TITLE
segfault when iterating over a vec with python 2.7

### ISSUE THREAD

**Issue by phil-el** [Zuzu-Typ/PyGLM#16]
shortest script to reproduce the problem:

```python
import glm

while True:
    for _ in glm.vec4(1.0):
        pass
```
This fragment of code segfault after a few iteration with python 2.7, backtrace is:
```
#0  0x00007f8b342d59c0 in PyCode_Type () from /usr/lib64/libpython2.7.so.1.0
#1  0x00007f8b3405dedf in ?? () from /usr/lib64/libpython2.7.so.1.0
#2  0x00007f8b33fcb3d6 in ?? () from /usr/lib64/libpython2.7.so.1.0
#3  0x00007f8b3405e187 in ?? () from /usr/lib64/libpython2.7.so.1.0
#4  0x00007f8b3405f0db in _PyObject_GC_Malloc ()
   from /usr/lib64/libpython2.7.so.1.0
#5  0x00007f8b3405f176 in _PyObject_GC_NewVar ()
   from /usr/lib64/libpython2.7.so.1.0
#6  0x00007f8b33fcbc6f in PyTuple_New () from /usr/lib64/libpython2.7.so.1.0
#7  0x00007f8b34041bde in ?? () from /usr/lib64/libpython2.7.so.1.0
#8  0x00007f8b3404107f in ?? () from /usr/lib64/libpython2.7.so.1.0
#9  0x00007f8b340420f7 in Py_BuildValue () from /usr/lib64/libpython2.7.so.1.0
#10 0x00007f8b2f308ac9 in tvec4_geniter (self=<optimized out>)
    at type_vec4.h:986
#11 0x00007f8b33f6a1fe in PyObject_GetIter ()
   from /usr/lib64/libpython2.7.so.1.0
#12 0x00007f8b340195cf in PyEval_EvalFrameEx ()
   from /usr/lib64/libpython2.7.so.1.0
#13 0x00007f8b34021d4c in PyEval_EvalCodeEx ()
   from /usr/lib64/libpython2.7.so.1.0
#14 0x00007f8b34021e69 in PyEval_EvalCode ()
   from /usr/lib64/libpython2.7.so.1.0
#15 0x00007f8b3404601a in PyRun_FileExFlags ()
   from /usr/lib64/libpython2.7.so.1.0
#16 0x00007f8b340473a7 in PyRun_SimpleFileExFlags ()
   from /usr/lib64/libpython2.7.so.1.0
#17 0x00007f8b3405d89e in Py_Main () from /usr/lib64/libpython2.7.so.1.0
#18 0x00007f8b3323e7d0 in __libc_start_main () from /lib64/libc.so.6
#19 0x0000000000400779 in _start ()
```
with python3 I only see a rare segfault when killing the script with Ctrl-C, the backtrace is:
```
#0  0x00006465736f6c63 in ?? ()
#1  0x00007fa222f3339f in ?? () from /usr/lib64/libpython3.6m.so.1.0
#2  0x00007fa222e625b6 in ?? () from /usr/lib64/libpython3.6m.so.1.0
#3  0x00007fa222f32707 in ?? () from /usr/lib64/libpython3.6m.so.1.0
#4  0x00007fa222f33769 in PyGC_Collect () from /usr/lib64/libpython3.6m.so.1.0
#5  0x00007fa222f10643 in Py_FinalizeEx () from /usr/lib64/libpython3.6m.so.1.0
#6  0x00007fa222f31663 in Py_Main () from /usr/lib64/libpython3.6m.so.1.0
#7  0x0000000000400b92 in main ()
```

A part of the python 2.7 backtrace is not reliable, sometime the bt does not contains tvec4_geniter nor any glm function but near the top of the bt there is always some python runtime call related to memory alloc/dealloc or garbage collection. Look like the vec4 iterator interface mess up the python memory allocator.

**Comment by phil-el** [comment]
See also issue https://github.com/Zuzu-Typ/PyGLM/issues/6 as with python3 this simple script leak very quickly.

**Comment by Zuzu-Typ** [comment]
Thanks for your report!

The reason for this memory leak are a few non-Py_DECREF-d tuples.

I'll release a fix very soon.
