### ISSUE TITLE
dmat4*vec4 or mat4*dvec4 compatibility

### ISSUE THREAD

**Issue by pepcots** [Zuzu-Typ/PyGLM#46]
```
>>> glm.mat4(1.0) * glm.vec4(1.0)
vec4( 1, 1, 1, 1 )
>>> glm.mat4(1.0) * glm.dvec4(1.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for *: 'glm.vec' and 'glm.mat4x4'
>>> glm.dmat4(1.0) * glm.vec4(1.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for *: 'glm.vec' and 'glm.dmat4x4'
>>> glm.dmat4(1.0) * glm.dvec4(1.0)
dvec4( 1, 1, 1, 1 )
```
Thanks!

**Comment by Zuzu-Typ** [comment]
In [glm](https://github.com/g-truc/glm), the only supported operand types for mat4 * vec4 are specified as follows:
([quote](https://github.com/g-truc/glm/blob/master/glm/detail/type_mat4x4.hpp#L148-L152))
```C++
template<typename T, qualifier Q>
GLM_FUNC_DECL typename mat<4, 4, T, Q>::col_type operator*(
        mat<4, 4, T, Q> const& m, 
        typename mat<4, 4, T, Q>::row_type const& v
);

template<typename T, qualifier Q>
GLM_FUNC_DECL typename mat<4, 4, T, Q>::row_type operator*(
        typename mat<4, 4, T, Q>::col_type const& v, 
        mat<4, 4, T, Q> const& m
);
```
Which translates to 
`mat4<of type T> * vec4<of type T>`
and
`vec4<of type T> * mat4<of type T>`,
where T has to be equal.

GLM-types of different datatypes are generally incompatible, with the only exception being the initialization.

**Comment by pepcots** [comment]
ok, sorry for open an issue and thank you for answering me.
